version: '3.1'
services:
  stacksdb:
    image: mysql:8.0
    ports:
      - '8889:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: stacks
      MYSQL_USER: stacks
      MYSQL_PASSWORD: stacks
      MYSQL_ROOT_PASSWORD: stacks
    volumes:
      - ./dump/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default
  www:
    build:
      context: .
      dockerfile: ./Dockerfile-www
    ports:
      - '8888:80'
    volumes:
      - ./www:/var/www/html/
    links:
      - stacksdb
    networks:
      - default
  adminer:
    image: adminer:latest
    depends_on: 
      - stacksdb
    ports:
      - '8887:8080'
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: stacksdb
      ADMINER_DEFAULT_DB_NAME: stacks
      ADMINER_DESIGN: nette 
      ADMINER_PLUGINS: tables-filter tinymce
volumes:
  persistent: